name: Semantic Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug the error
        continue-on-error: true
        run: |
          sudo apt-get update && sudo apt-get install -y python3 git
          pip install flit
          flit build
          git status
